### ISSUE TITLE
Add dockerfile 

### ISSUE THREAD

**Issue by rafaelrubbioli** [rafaelrubbioli/expenses#32]
path `/buid/Dockerfile`

**Comment by Ayushchaudhary-Github** [comment]
I haven't create a docker file before can you give me some suggestion.

**Comment by rafaelrubbioli** [comment]
Sure! You can read the [reference](https://docs.docker.com/engine/reference/builder/) to get the hang of it.

Some tips:
For go, the base image is `golang:{version, like 1.17}`
and the build command in this case is `CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" cmd/server/server.go`

heres an example: https://github.com/rafaelrubbioli/terminator/blob/master/Dockerfile

**Comment by gopheramit** [comment]
Hey @rafaelrubbioli dockerfile already exists for this project,is it wrong or needs improvement?

**Comment by rafaelrubbioli** [comment]
I forgot it was merged before! Thanks
