### ISSUE TITLE
Update go to 1.17 and use embed to extract query files

### ISSUE THREAD

**Issue by rafaelrubbioli** [rafaelrubbioli/expenses#33]
- [ ] Update go to 1.17
- [ ] extract service/internal/repository queries to {repository name}.sql
- [ ] use goyesql to parse queries github.com/nleof/goyesql
- [ ] use go embed to embed .sql files

**Comment by VictorAssunc** [comment]
Hi @rafaelrubbioli , can I work on it?

**Comment by rafaelrubbioli** [comment]
> Hi @rafaelrubbioli , can I work on it?

sure!
